sources:
  source_0:
    noise: 0.0
    type: gamma
    units: cps
    value: 500.0
    x: 0
    y: 0
    z: 0
  source_1:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 500.0
    x: 0
    y: 0
    z: 0
  source_2:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 5000.0
    x: 0
    y: 0
    z: 0
  source_3:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 200.0
    x: 0
    y: 0
    z: 0
  source_4:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 900.0
    x: 0
    y: 0
    z: 0
  source_5:
    noise: 0.0
    type: gamma
    units: Sv/h
    value: 100.0
    x: 0
    y: 0
    z: 0
