sensors:
  sensor_0:
    type: "gamma"
    range: 100.0
    poisson: false
    collimated: true
    sensitivity_function: ""
    mu: 0.0
    sigma: 0.0
    angle_limit: 3.2
  sensor_1:
    type: "gamma"
    range: 100.0
    poisson: false
    collimated: true
    sensitivity_function: ""
    mu: 0.0
    sigma: 0.0
    angle_limit: 3.2
  sensor_2:
    type: "gamma"
    range: 100.0
    poisson: false
    collimated: true
    sensitivity_function: ""
    mu: 0.0
    sigma: 0.0
    angle_limit: 3.2
  sensor_3:
    type: "gamma"
    range: 100.0
    poisson: false
    collimated: true
    sensitivity_function: ""
    mu: 0.0
    sigma: 0.0
    angle_limit: 3.2
  sensor_4:
    type: "gamma"
    range: 100.0
    poisson: false
    collimated: true
    sensitivity_function: ""
    mu: 0.0
    sigma: 0.0
    angle_limit: 3.2
